### PR TITLE
simple demo, play a tune on the keyboard

### PR DESCRIPTION
**Pull request by jrit**

### CODE REVIEW

**Comment by scottferg** [comment]
Think about serving this up on Github Pages? It's probably the best use-case of it that we've had.

**Comment by scottferg** [comment]
Changelist LGTM

**Comment by jrit** [comment]
Yeah, I was looking at it

On January 11, 2015 10:14:18 PM CST, Scott Ferguson <notifications@github.com> wrote:
>Think about serving this up on Github Pages? It's probably the best
>use-case of it that we've had.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vokal/yeep/pull/7#issuecomment-69528594

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by jrit** [comment]
posted http://vokal.github.io/yeep/

**Pull request merged**
